"""Initial migration

Revision ID: 572d8ce58f0a
Revises: bc49281cc7bd
Create Date: 2025-05-10 08:03:11.885676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572d8ce58f0a'
down_revision = 'bc49281cc7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('date_arrivee', sa.Date(), nullable=False),
    sa.Column('date_depart', sa.Date(), nullable=False),
    sa.Column('nombre_personnes', sa.Integer(), nullable=False),
    sa.Column('methode_paiement', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('prix_total', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_room_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('type_evenement', sa.String(length=50), nullable=False),
    sa.Column('date_evenement', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('nombre_invites', sa.Integer(), nullable=False),
    sa.Column('methode_paiement', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('prix_total', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('event_room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_room_id'], ['event_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('date_arrivee', sa.Date(), nullable=False),
    sa.Column('date_depart', sa.Date(), nullable=False),
    sa.Column('nombre_personnes', sa.Integer(), nullable=False),
    sa.Column('methode_paiement', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('prix_total', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_reservations')
    op.drop_table('event_room_reservations')
    op.drop_table('apartment_reservations')
    # ### end Alembic commands ###
