"""Renommage de verification_code en reset_token

Revision ID: 7fd4aa3fe989
Revises: 66f955568bb0
Create Date: 2025-07-08 07:44:53.844715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fd4aa3fe989'
down_revision = '66f955568bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', mysql.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
